POST localhost:8080/api/v1/items
Content-Type: application/json
Cookie: queue-wait-order-token=b5deed527c1b49f3307e36ab221cb4c42a543cd811a03a00ed6cf71a5786da97;

{
  "name" : "모자11",
  "price" : "10000",
  "stock" : "100"
}

###

GET localhost:8080/api/v1/items/1
Content-Type: application/json
Cookie: queue-wait-order-token=b5deed527c1b49f3307e36ab221cb4c42a543cd811a03a00ed6cf71a5786da97;

###

POST localhost:8080/api/v1/items/1/decrease-stock
Content-Type: application/json

{
  "decreaseCount" : 1
}

###

DELETE localhost:8080/api/v1/items/1
Content-Type: application/json
