POST localhost:8080/api/v1/items
Content-Type: application/json
Cookie: queue-wait-order-token=f4c3e2d040948546a221e8b754714d347774057790a22e8f579f21bf7d4bf3e3;

{
  "name" : "모자11",
  "price" : "10000",
  "stock" : "100"
}

###

GET localhost:8080/api/v1/items/1
Content-Type: application/json
Cookie: queue-wait-order-token=f4c3e2d040948546a221e8b754714d347774057790a22e8f579f21bf7d4bf3e3;

###

POST localhost:8080/api/v1/items/1/decrease-stock
Content-Type: application/json

{
  "decreaseCount" : 1
}

###

DELETE localhost:8080/api/v1/items/1
Content-Type: application/json
