POST localhost:8080/api/v1/orders
Content-Type: application/json
Cookie: queue-wait-order-token=b5deed527c1b49f3307e36ab221cb4c42a543cd811a03a00ed6cf71a5786da97;

{
  "itemId" : "1",
  "quantity" : "1"
}
