GET localhost:8080/api/v1/queue?queue=order&userId=1
Content-Type: application/json

###

GET localhost:8080/api/v1/queue/rank?queue=order
Content-Type: application/json
Cookie: queue-wait-order-token=b5deed527c1b49f3307e36ab221cb4c42a543cd811a03a00ed6cf71a5786da97;

###

GET localhost:8080/api/v1/queue/allowed?queue=order&userId=1
Content-Type: application/json
Cookie: queue-wait-order-token=b5deed527c1b49f3307e36ab221cb4c42a543cd811a03a00ed6cf71a5786da97;
