GET localhost:8083/api/v1/queue?queue=order&userId=1
Content-Type: application/json

###

GET localhost:8083/api/v1/queue/rank?queue=order
Content-Type: application/json
Cookie: queue-wait-order-token=e047e3282cef454d1f2a8945e39ffbfbe14cdbda88ddf1f9bfdaa85a68398ee5;
