server:
  port: 8080

spring:
  application:
    name: gateway-service

  profiles:
    active: local

  config:
    import: optional:configserver:http://localhost:8887

  cloud:
    gateway:
      routes:
        - id: item-api
          uri: lb://ITEM-API
          predicates:
            - Path=/api/v1/items/**

        - id: order-api
          uri: lb://ORDER-API
          predicates:
            - Path=/api/v1/orders/**

        - id: payment-api
          uri: lb://PAYMENT-API
          predicates:
            - Path=/api/v1/payments/**

        - id: queue-api
          uri: lb://QUEUE-API
          predicates:
            - Path=/api/v1/queue/**
