version: '3.8'
services:
  db:
    image: mysql:latest
    container_name: ecommerce_mysql
    environment:
      MYSQL_DATABASE: 'ecommerce'
      MYSQL_USER: 'test'
      MYSQL_PASSWORD: '1234'
      MYSQL_ROOT_PASSWORD: '1234'
    ports:
      - '3306:3306'
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d

  redis:
    image: redis:latest
    container_name: ecommerce_redis
    ports:
      - 6379:6379
    volumes:
      - ./redis/data:/data
      - ./redis/conf/redis.conf:/usr/local/conf/redis.conf
    labels:
      - "name=redis"
      - "mode=standalone"

    command: redis-server /usr/local/conf/redis.conf
