server:
  port: 8887

spring:
  application:
    name: config-service

  cloud:
    config:
      server:
        git:
          uri: https://github.com/zzangoobrother/stock-order-project
    bus:
      enabled: true
    stream:
      kafka:
        binder:
          brokers: localhost:10000,localhost:10001,localhost:10002

management:
  endpoints:
    web:
      exposure:
        include: busrefresh, refresh
